from app.tools.project_tools import PAPER_AGENT_TOOLS, PROJECT_RETRIEVAL_TOOLS, PROJECT_WRITING_TOOLS
from app.tools.skill_tools import WRITING_SKILL_TOOLS

PAPER_MANAGER_TOOLS = [
    *PROJECT_RETRIEVAL_TOOLS,
    *WRITING_SKILL_TOOLS,
    *PROJECT_WRITING_TOOLS,
]

WRITING_AGENT_TOOLS = [
    *PROJECT_RETRIEVAL_TOOLS,
    *WRITING_SKILL_TOOLS,
    *PROJECT_WRITING_TOOLS,
]

__all__ = [
    "PAPER_AGENT_TOOLS",
    "PAPER_MANAGER_TOOLS",
    "WRITING_AGENT_TOOLS",
]
